const actionType = Object.freeze({
    //app
    APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
    SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",

    //admin
    ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
    ADMIN_LOGIN_FAILURE: "ADMIN_LOGIN_FAILURE",
    PROCESS_LOGOUT: "PROCESS_LOGOUT",

    //user
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
});

export default actionType;
